services:
  web:
    image: project-paws:django
    build:
      context: ../
      dockerfile: ./docker/frontend.Dockerfile
    volume:
      - shared-socket:/var/run/app
    #ports:
    #  - 5000:5000
  # TODO: Add Database
  # TODO: Add Redis but Valkey is faster
  # TODO: Add Caddy with custom files
  # OPTIONAL: Add apache solr for search
volumes:
  # To make things faster between uwsgi and caddy/nginx we
  # are using unix sockts.
  shared-sockets: {}
