name: build-project-paws
run-name: Project-Paws - ${{ github.actor }} by ${{ github.event_name }} ${{ github.ref }}
on:
  push:
    branches:
      - "main"
    paths:
      - "!INFO.md"
      - "!README.md"
      - "!LICENSE"
  pull_request:
    branches:
      - main
    paths:
      - "!INFO.md"
      - "!LICENSE"
      - "!README.md"
  workflow_dispatch: {}
env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #      - name: Login to Docker Hub
      #        uses: docker/login-action
      #        with:
      #          username: ${{ secrets.DOCKERHUB_USERNAME }}
      #          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Registery
        uses: docker/login-action@v3
        id: github-registry
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5
        id: version
      #        with:
      #          change_path: "project-paws"
      #          namespace: "project-paws"

      - name: Echo Version
        run: echo "Version would be ${{ steps.version.outputs.version }}"

      - name: Build and Push Docker PR
        if: github.event_name == 'pull_request'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and Push Docker Master Branch
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: "."
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Tag Release (vX.Y.Z)
        if: github.event_name != 'pull_request'
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}
