name: build-project-paws
run-name: Project-Paws - ${{ github.actor }} by ${{ github.event_name }} ${{ github.head_ref }}

on:
  push:
    branches:
      - "main"
    paths:
      - "*"
      - "!INFO.md"
      - "!README.md"
      - "!LICENSE"
  pull_request:
    branches:
      - main
    paths:
      - "*"
      - "!INFO.md"
      - "!LICENSE"
      - "!README.md"
  workflow_dispatch: {}

env:
  GITHUB_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-project-paws:
    runs-on: arc-runner-set

    permissions:
      packages: write
      contents: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registery
        uses: docker/login-action@v3
        id: github-registry
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Release Semantic Version
        uses: ietf-tools/semver-action@v1
        id: semver
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}},value=${{ steps.semver.outputs.nextStrict }}
          images: ${{ env.GITHUB_REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Echo Version
        run: echo "Version would be ${{ steps.semver.outputs.next }}"

      - name: Build and Push Docker PR
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Tag git Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.semver.outputs.next }}
          git push origin ${{ steps.semver.outputs.next }}
